; ======== architecture independent ========
[custom]
lib_deps =
  https://github.com/Blizzard26/Seeed_Arduino_CAN
build_flags =
  ${KNX_TP.build_flags}

[custom_develop]
extends = custom
build_flags =
  ${custom.build_flags}
  -D OPENKNX_HEARTBEAT
  -D OPENKNX_RUNTIME_STAT
  -D OPENKNX_LOOPTIME_WARNING=15

[custom_releases]
extends = custom
build_flags =
  ${custom.build_flags}
  -D OPENKNX_WATCHDOG
  -D OPENKNX_LOOPTIME_WARNING=20

; ======== RP2040 ========
[RP2040_custom]
extends = RP2040
lib_deps =
  ${custom.lib_deps}
build_flags =
  -D SERIAL_DEBUG=Serial

; this config block is for specifying options that are valid for all
; RP2040-based develop/debug builds
[RP2040_custom_develop]
extends = RP2040_develop, RP2040_custom, custom_develop
build_flags =
  ${RP2040_develop.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_develop.build_flags}
  ${KNX_TP.build_flags}

; this config block is for specifying options that are valid for all RP2040-based release builds
[RP2040_custom_releases]
extends = RP2040_releases, RP2040_custom, custom_releases
build_flags =
  ${RP2040_releases.build_flags}
  ${RP2040_custom.build_flags}
  ${custom_releases.build_flags}
  ${KNX_TP.build_flags}

; Development environments
[env:dev_KNX2HOVALGATEWAY]
extends = RP2040_custom_develop, RP2040_2MB
board = seeed_xiao_rp2040
build_flags =
  ${RP2040_custom_develop.build_flags}

; Release environments
[env:release_KNX2HOVALGATEWAY]
extends = RP2040_custom_releases, RP2040_2MB
board = seeed_xiao_rp2040
build_flags =
  ${RP2040_custom_releases.build_flags}
